#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include "ssd1306.h"

    /**
     * @brief Disable terminal emulation mode on the given TTY device.
     *
     * @param tty Pointer to the TTY context associated with the SSD1306 display.
     */
    void disable_tty_mode(ssd1306_tty_t *tty);

    /**
     * @brief Enable terminal emulation mode on the given TTY device.
     *
     * @param tty Pointer to the TTY context associated with the SSD1306 display.
     */
    void enable_tty_mode(ssd1306_tty_t *tty);

    /**
     * @brief Reset the PAL interface connected to the TTY device.
     *
     * @param tty Pointer to the TTY context used for PAL interaction.
     */
    void reset_pal(ssd1306_tty_t *tty);

    /**
     * @brief Count edge transitions on a GPIO pin within a specified time window.
     *
     * @param pin GPIO pin number to monitor.
     * @param window_us Duration to monitor, in microseconds.
     * @return Number of rising or falling edges detected within the window.
     */
    int get_edges(int pin, int window_us);

    /**
     * @brief Retrieve a character from user input.
     *
     * Typically called by polling a UART or keyboard interface.
     *
     * @return The received character, or -1 if no character is available.
     */
    int user_getchar(void);

    /**
     * @brief Send a single character to the PAL system.
     *
     * This function also reads the echo back from the PAL system and echos
     * it to the user devices.  It adds color to the output for debugging
     * purposes.
     *
     * It also handles all of the internal timing delays.
     *
     * @note It is not intended to be called for user-generated input.
     *
     * @param ch Character to transmit.
     */
    void upload_char_to_pal(char ch);

    /**
     * @brief Send a null-terminated string to the PAL system.
     *
     * This function uses upload_char_to_pal() to transmit each character
     * in the given string. It also reads back any response generated by
     * the PAL in response to the uploaded line.
     *
     * Specifically, it checks for the presence of "ERR" or "KIM" in the response
     * to determine whether an error occurred.
     *
     * @param line Pointer to the null-terminated string to transmit.
     *
     * @note This function is not intended to be used for user-generated input.
     * @see upload_char_to_pal()
     */

    void upload_line_to_pal(const char *line);

    /**
     * @brief Send a single character to the PAL system.
     *
     * This function is meant for standard user input and does not
     * automatically add delays or do any other processing.
     *
     * @param ch Character to send.
     *
     * @note This function *is* intended to be used for user-generated input.
     */
    void pal_putc(char ch);

    /* @brief Retrieve a character from the PAL.
     *
     * Typically called by polling a UART or keyboard interface.
     *
     * @return The received character, or -1 if no character is available.
     */

    int pal_getchar();

    /**
     * @brief Send a single character to the PAL system.
     *
     * This function is meant for standard user input and does not
     * automatically add delays or do any other processing.
     *
     * @param ch Character to send.
     *
     * @note This function *is* intended for general use.
     */
    void u_putc(char ch);

    /**
     * @brief printf to the user devices
     *
     *
     * @param fmt The format string
     *
     */

    void u_printf(const char *fmt, ...);

#ifdef __cplusplus
}
#endif
